### ISSUE TITLE
Magic numbers 

### ISSUE THREAD

**Issue by yuryev89** [egupsv/web-task-manager#12]
1. `com.example.web_task_manager.servlet.UsersServlet#createUser(){
        if (addParam == 1) {
}`

2. `com.example.web_task_manager.servlet.UserServlet#checkDeleteStatus(){
deleteStatus == 1
}`
3. `targetUserName.length() > 4 ` why user name should be more then 4?

**Comment by daillie** [comment]
1 & 2. delete 
3. fixed by adding const param in USER class
