### ISSUE TITLE
Storing password in cookies

### ISSUE THREAD

**Issue by yuryev89** [egupsv/web-task-manager#4]
Why do you send this to a client? First of all, this is not secure, also you don't use it anywhere
`            cookieController.createCookie(response, CookieName.PASSWORD, encPassword);`

![image](https://user-images.githubusercontent.com/12292599/117868102-41058f80-b2aa-11eb-99c5-83fcb7118acc.png)

**Comment by egupsv** [comment]
fixed with commit 75bc376b4eab3b32a7dcd556938461cad69ec580
