### ISSUE TITLE
Global Static variable - TryChecker

### ISSUE THREAD

**Issue by yuryev89** [egupsv/web-task-manager#7]
Following static method operates with global static variable com.example.web_task_manager.servlet.TryChecker#setPropertyOfSignupDiv

Issues: 
1. This is the static variable which means it relates to class and it may have only one value for the whole application
2. Which leads us to another issue, that it can be simply modified from another thread and we get floating bug in multi users application 

PS moreover i don't see any usage of it.. Some redundant code.

**Comment by egupsv** [comment]
Class was removed with commit 'repair filter'
